### PR TITLE
[dependabot] add config file

### PR DESCRIPTION
**Pull request by jwhui**
To enable automatic daily updates of openthread submodule.

### CODE REVIEW

**Review by LuDuda — APPROVED** [review]
Wow, this is great!

FYI @MarekPorwisz

**Comment by jwhui** [comment]
@LuDuda @MarekPorwisz , I can also set this up to automatically tag someone for review on the automated PR submissions. Is there anyone you'd like to add?

**Comment by MarekPorwisz** [comment]
Please auto tag me, and I will try to pass it to anyone available.

**Review by MarekPorwisz — APPROVED** [review]

**Comment by jwhui** [comment]
> Please auto tag me, and I will try to pass it to anyone available.

Thanks, @MarekPorwisz !

**Pull request merged**
