### PR TITLE
[nrfx] upgrade to version 1.9.0

### PR DESCRIPTION
**Pull request by edmont**
Upgrade nrfx from 1.8.0 to 1.9.0.

This includes new MDK version 8.40.3. Then further upgrade MDK from 8.40.3 to 8.47.0 for GCC.

Also cherry-picked a couple of fixes included after 1.8.0 bump.

### CODE REVIEW

**Review by LuDuda — APPROVED** [review]

**Comment by Irving-cl** [comment]
Hi @edmont,

I had a try on this. But I still got this issue:
* I built a NCP FW and flash it to the device with JLink
* I triggered a pin reset
* I started a JLinkGDBServer and attach GDB to it. And I got:

```
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./ot-ncp.elf...
(gdb) target remote localhost:2331
Remote debugging using localhost:2331
0xfffffffe in ?? ()
(gdb) q
```

As a contrast, I tried to manually update it to 8_47_0 and I don't have this problem. Could you help take a look?

**Comment by edmont** [comment]
Hi @Irving-cl, were you able to give a try to the updated PR?

**Review by Irving-cl — APPROVED** [review]
LGTM 👍 

I've verified it locally and don't have the issue now. Thanks!

**Comment by edmont** [comment]
@jwhui not sure it was good idea to squash all the commits. I separated them on purpose to have a clear track of what has actually changed beyond nrfx 1.8.0.

**Comment by jwhui** [comment]
> @jwhui not sure it was good idea to squash all the commits. I separated them on purpose to have a clear track of what has actually changed beyond nrfx 1.8.0.

Sorry, it wasn't clear to me that you wanted to keep the commits separate. How should we handle this now?

**Comment by edmont** [comment]
If rewriting history is not easy I can keep my branch non-deleted for reference.

**Comment by jwhui** [comment]
> If rewriting history is not easy I can keep my branch non-deleted for reference.

Some options:
1. Submit a new PR that reverts the last commit.
2. Force push to remove last commit from main branch.

**Comment by edmont** [comment]
Just force-pushed my branch, is that what you mean?

**Comment by jwhui** [comment]
> Just force-pushed my branch, is that what you mean?

main branch is protected, but I can override it. But if you prefer not to rewrite history, we could submit a PR that reverts the last commit. Let me know what you prefer.

**Comment by edmont** [comment]
I'm fine with rewriting history.

**Comment by edmont** [comment]
Replaced by https://github.com/openthread/ot-nrf528xx/pull/441

**Pull request merged**
